#!/sbin/sh
# 懂球帝广告屏蔽模块 - 安装界面 v1.4
ui_print ""
ui_print "  ┌─────────────────────────────────┐"
ui_print "  │                                 │"
ui_print "  │     懂球帝广告屏蔽 v1.4         │"
ui_print "  │                                 │"
ui_print "  │    专为懂球帝APP定制            │"
ui_print "  │    拦截主流广告SDK              │"
ui_print "  │                                 │"
ui_print "  └─────────────────────────────────┘"
ui_print ""
ui_print "  📋 功能概览:"
ui_print "  ├ 开机自动清理16个广告缓存目录"
ui_print "  ├ 锁定广告目录(000权限)"
ui_print "  ├ 穿山甲(Pangle)广告拦截"
ui_print "  ├ 广点通(GDT)广告拦截"
ui_print "  ├ 倍孜(Beizi)广告拦截"
ui_print "  ├ 快手广告拦截"
ui_print "  ├ Google Ads 拦截"
ui_print "  ├ Unity Ads / Vungle 拦截"
ui_print "  ├ AppLovin / Mintegral 拦截"
ui_print "  ├ AdColony / Chartboost 拦截"
ui_print "  ├ IronSource / Tapjoy 拦截"
ui_print "  └ 极光推送 拦截"
ui_print ""
ui_print "  ⚙️ 安装信息:"
ui_print "  ├ 模块作者: Sinc"
ui_print "  ├ 版本号: v1.4"
ui_print "  └ 安装路径: $MODPATH"
ui_print ""
ui_print "  🔧 设置权限..."
set_perm_recursive $MODPATH 0 0 0755 0644
set_perm $MODPATH/service.sh 0 0 0755
set_perm $MODPATH/system/bin/dongqiudi-adblock.sh 0 0 0755
ui_print ""
ui_print "  ✅ 模块安装完成，感谢使用！"
ui_print "  💡 重启手机后生效：自动清理广告缓存+锁定目录+iptables拦截"
ui_print ""